<a href="https://colab.research.google.com/github/Prakharshrivas/Hacktoberfest-2021/blob/master/chunkss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Bondora_raw.csv to Bondora_raw (1).csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Bondora_raw.csv")
df.head()

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (34,37,38,80,82,83,89,90) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ReportAsOfEOD,LoanId,LoanNumber,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,UserName,NewCreditCustomer,...,PreviousEarlyRepaymentsCountBeforeLoan,GracePeriodStart,GracePeriodEnd,NextPaymentDate,NextPaymentNr,NrOfScheduledPayments,ReScheduledOn,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost,ActiveLateLastPaymentCategory
0,2020-01-27,F0660C80-83F3-4A97-8DA0-9C250112D6EC,659,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,KARU,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1,2020-01-27,978BB85B-1C69-4D51-8447-9C240104A3A2,654,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,koort681,False,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,2020-01-27,EA44027E-7FA7-4BB2-846D-9C1F013C8A22,641,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,0ie,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,180+
3,2020-01-27,CE67AD25-2951-4BEE-96BD-9C2700C61EF4,668,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,Alyona,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
4,2020-01-27,9408BF8C-B159-4D6A-9D61-9C2400A986E3,652,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,Kai,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,180+

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134529 entries, 0 to 134528
Columns: 112 entries, ReportAsOfEOD to ActiveLateLastPaymentCategory
dtypes: bool(3), float64(56), int64(14), object(39)
memory usage: 112.3+ MB

In [ ]:
df.columns

Index(['ReportAsOfEOD', 'LoanId', 'LoanNumber', 'ListedOnUTC',
       'BiddingStartedOn', 'BidsPortfolioManager', 'BidsApi', 'BidsManual',
       'UserName', 'NewCreditCustomer',
       ...
       'PreviousEarlyRepaymentsCountBeforeLoan', 'GracePeriodStart',
       'GracePeriodEnd', 'NextPaymentDate', 'NextPaymentNr',
       'NrOfScheduledPayments', 'ReScheduledOn', 'PrincipalDebtServicingCost',
       'InterestAndPenaltyDebtServicingCost', 'ActiveLateLastPaymentCategory'],
      dtype='object', length=112)

In [ ]:
missing_data = pd.DataFrame({'total_missing': df.isnull().sum(), 'perc_missing': (df.isnull().sum()/134528)*100})
missing_data

                                     total_missing  perc_missing
ReportAsOfEOD                                    0      0.000000
LoanId                                           0      0.000000
LoanNumber                                       0      0.000000
ListedOnUTC                                      0      0.000000
BiddingStartedOn                                 0      0.000000
...                                            ...           ...
NrOfScheduledPayments                        36741     27.311043
ReScheduledOn                                94207     70.027801
PrincipalDebtServicingCost                   75400     56.047812
InterestAndPenaltyDebtServicingCost          75400     56.047812
ActiveLateLastPaymentCategory                82279     61.161245

[112 rows x 2 columns]

In [ ]:
df.describe()

,LoanNumber,BidsPortfolioManager,BidsApi,BidsManual,ApplicationSignedHour,ApplicationSignedWeekday,VerificationType,LanguageCode,Age,Gender,...,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsBefoleLoan,PreviousEarlyRepaymentsCountBeforeLoan,NextPaymentNr,NrOfScheduledPayments,PrincipalDebtServicingCost,InterestAndPenaltyDebtServicingCost
count,1.345290e+05,134529.000000,134529.000000,134529.000000,134529.000000,134529.000000,134484.000000,134529.000000,134529.000000,134484.000000,...,134529.000000,134529.000000,134529.000000,91368.000000,58026.000000,134529.000000,97788.000000,97788.000000,59129.000000,59129.000000
mean,9.449392e+05,966.452876,29.111664,559.332590,13.374640,3.907908,2.817257,2.827874,40.819295,0.442097,...,701.567107,1.487620,2868.652401,928.395548,320.743805,0.069903,5.178795,50.126795,5.264702,89.851455
std,4.786738e+05,1355.686016,150.159148,750.360512,4.992375,1.726192,1.407908,1.959802,12.348693,0.636083,...,2514.595572,2.396148,4507.046575,2042.348751,1561.799076,0.359461,7.674427,12.519530,57.800582,287.449052
min,3.700000e+01,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,-2.660000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,6.206790e+05,155.000000,0.000000,96.000000,10.000000,2.000000,1.000000,1.000000,31.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,36.000000,0.000000,0.000000
50%,9.235970e+05,465.000000,0.000000,317.000000,13.000000,4.000000,4.000000,3.000000,40.000000,0.000000,...,0.000000,1.000000,396.354100,197.980000,0.000000,0.000000,3.000000,60.000000,0.000000,0.000000
75%,1.311025e+06,1218.000000,5.000000,729.000000,17.000000,5.000000,4.000000,4.000000,50.000000,1.000000,...,202.900000,2.000000,4250.000000,780.950000,0.000000,0.000000,7.000000,60.000000,0.000000,17.330000
max,1.855339e+06,10625.000000,7570.000000,10630.000000,23.000000,7.000000,4.000000,22.000000,77.000000,2.000000,...,64494.770000,25.000000,53762.000000,34077.420000,48100.000000,11.000000,60.000000,72.000000,3325.330000,5295.290000

In [ ]:
drop_list=df.columns[df.isnull().mean()*100>=50].tolist()
drop_list

['ContractEndDate',
 'NrOfDependants',
 'EmploymentPosition',
 'WorkExperience',
 'PlannedPrincipalTillDate',
 'CurrentDebtDaysPrimary',
 'DebtOccuredOn',
 'CurrentDebtDaysSecondary',
 'DebtOccuredOnForSecondary',
 'DefaultDate',
 'PlannedPrincipalPostDefault',
 'PlannedInterestPostDefault',
 'EAD1',
 'EAD2',
 'PrincipalRecovery',
 'InterestRecovery',
 'EL_V0',
 'Rating_V0',
 'EL_V1',
 'Rating_V1',
 'Rating_V2',
 'ActiveLateCategory',
 'CreditScoreEsEquifaxRisk',
 'CreditScoreFiAsiakasTietoRiskGrade',
 'PrincipalWriteOffs',
 'InterestAndPenaltyWriteOffs',
 'PreviousEarlyRepaymentsBefoleLoan',
 'GracePeriodStart',
 'GracePeriodEnd',
 'NextPaymentDate',
 'ReScheduledOn',
 'PrincipalDebtServicingCost',
 'InterestAndPenaltyDebtServicingCost',
 'ActiveLateLastPaymentCategory']

In [ ]:
df[drop_list].isnull().mean()*100

ContractEndDate                        56.155922
NrOfDependants                         73.537304
EmploymentPosition                     73.173070
WorkExperience                         72.851950
PlannedPrincipalTillDate               59.518765
CurrentDebtDaysPrimary                 63.934914
DebtOccuredOn                          63.934914
CurrentDebtDaysSecondary               61.160791
DebtOccuredOnForSecondary              61.160791
DefaultDate                            68.099815
PlannedPrincipalPostDefault            68.099815
PlannedInterestPostDefault             68.099815
EAD1                                   68.099815
EAD2                                   68.099815
PrincipalRecovery                      68.099815
InterestRecovery                       68.099815
EL_V0                                  96.603706
Rating_V0                              96.603706
EL_V1                                  90.394636
Rating_V1                              90.394636
Rating_V2                              81.310349
ActiveLateCategory                     63.934914
CreditScoreEsEquifaxRisk               90.917200
CreditScoreFiAsiakasTietoRiskGrade     75.828260
PrincipalWriteOffs                     56.047395
InterestAndPenaltyWriteOffs            56.047395
PreviousEarlyRepaymentsBefoleLoan      56.867293
GracePeriodStart                       86.034238
GracePeriodEnd                         86.034238
NextPaymentDate                        51.204573
ReScheduledOn                          70.027280
PrincipalDebtServicingCost             56.047395
InterestAndPenaltyDebtServicingCost    56.047395
ActiveLateLastPaymentCategory          61.160791
dtype: float64

In [ ]:
df.drop(columns=drop_list,inplace=True)

In [23]:
df.drop(columns=['DateOfBirth','UserName','LoanId', 'LoanNumber','IncomeFromPrincipalEmployer', 'IncomeFromPension', 'IncomeFromFamilyAllowance', 'IncomeFromSocialWelfare',
                 'IncomeFromLeavePay', 'IncomeFromChildSupport', 'IncomeOther'],inplace=True)

In [24]:
df.head()

,ReportAsOfEOD,ListedOnUTC,BiddingStartedOn,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,LoanApplicationStartedDate,LoanDate,FirstPaymentDate,...,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan,NextPaymentNr,NrOfScheduledPayments
0,2020-01-27,2009-06-11 16:40:39,2009-06-11 16:40:39,0,0,115.0410,True,2009-06-11 16:40:39,2009-06-16,2009-07-27,...,115.0408,20.4222,0.00,0.00,1,83.0852,0.0000,0,NaN,NaN
1,2020-01-27,2009-06-10 15:48:57,2009-06-10 15:48:57,0,0,140.6057,False,2009-06-10 15:48:57,2009-06-15,2009-07-15,...,140.6057,2.0227,0.00,0.00,2,255.6467,258.6256,0,NaN,NaN
2,2020-01-27,2009-06-05 19:12:29,2009-06-05 19:12:29,0,0,319.5580,True,2009-06-05 19:12:29,2009-06-15,2009-07-27,...,203.1909,59.7626,116.35,414.07,0,0.0000,0.0000,0,NaN,NaN
3,2020-01-27,2009-06-13 12:01:20,2009-06-13 12:01:20,0,0,57.5205,True,2009-06-13 12:01:20,2009-06-15,2009-07-15,...,57.5205,18.7323,0.00,0.00,1,134.2144,0.0000,0,NaN,NaN
4,2020-01-27,2009-06-10 10:17:13,2009-06-10 10:17:13,0,0,319.5582,True,2009-06-10 10:17:13,2009-06-14,2009-07-27,...,319.5436,220.4200,0.00,0.00,1,146.9966,0.0000,0,NaN,NaN

In [26]:
df.drop(columns=['ReportAsOfEOD', 'ListedOnUTC', 'BiddingStartedOn', 'LoanApplicationStartedDate', 'LastPaymentOn',
                 'MonthlyPaymentDay','LoanDate', 'FirstPaymentDate', 'MaturityDate_Original','MaturityDate_Last','NextPaymentNr', 'NrOfScheduledPayments', 'ApplicationSignedHour', 'ApplicationSignedWeekday', 
                 'ActiveScheduleFirstPaymentReached', 'PlannedInterestTillDate', 'ExpectedLoss','LossGivenDefault',
                'ExpectedReturn', 'ProbabilityOfDefault', 'PrincipalOverdueBySchedule', 'StageActiveSince', 
                'ModelVersion', 'WorseLateCategory'], 
        inplace = True)

In [27]:
df.head()

,BidsPortfolioManager,BidsApi,BidsManual,NewCreditCustomer,VerificationType,LanguageCode,Age,Gender,Country,AppliedAmount,...,CreditScoreEsMicroL,CreditScoreEeMini,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,InterestAndPenaltyBalance,NoOfPreviousLoansBeforeLoan,AmountOfPreviousLoansBeforeLoan,PreviousRepaymentsBeforeLoan,PreviousEarlyRepaymentsCountBeforeLoan
0,0,0,115.0410,True,2.0,1,61,1.0,EE,319.5582,...,NaN,NaN,115.0408,20.4222,0.00,0.00,1,83.0852,0.0000,0
1,0,0,140.6057,False,2.0,1,48,1.0,EE,191.7349,...,NaN,NaN,140.6057,2.0227,0.00,0.00,2,255.6467,258.6256,0
2,0,0,319.5580,True,2.0,1,58,1.0,EE,319.5582,...,NaN,NaN,203.1909,59.7626,116.35,414.07,0,0.0000,0.0000,0
3,0,0,57.5205,True,2.0,1,23,1.0,EE,127.8233,...,NaN,NaN,57.5205,18.7323,0.00,0.00,1,134.2144,0.0000,0
4,0,0,319.5582,True,2.0,1,25,1.0,EE,319.5582,...,NaN,NaN,319.5436,220.4200,0.00,0.00,1,146.9966,0.0000,0